// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.PersonItemView = (function(_super) {
    __extends(PersonItemView, _super);

    function PersonItemView() {
      _ref = PersonItemView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PersonItemView.prototype.tagName = 'li';

    PersonItemView.prototype.initialize = function() {
      _.bindAll(this);
      return this.render();
    };

    PersonItemView.prototype.render = function() {
      this.$el.html("			<div class='box'>				<a data-route='/member/" + (this.model.get('uid')) + "'>					<img src='" + (Bolk.BlipRequest.photo_src(this.model.get('uid'), 150, 150)) + "' title='" + (this.model.get('name')) + "'/>				</a>			</div>			<a class='title' data-route='/member/" + (this.model.get('uid')) + "'>" + (this.model.get('name')) + "</a>		");
      return this;
    };

    return PersonItemView;

  })(Backbone.View);

}).call(this);
