// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.PersonItemView = (function(_super) {
    __extends(PersonItemView, _super);

    function PersonItemView() {
      _ref = PersonItemView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PersonItemView.prototype.tagName = 'li';

    PersonItemView.prototype.initialize = function() {
      return _.bindAll(this);
    };

    PersonItemView.prototype.render = function() {
      return $(this.el).html("<a href='" + (this.model.get('href')) + "'>" + (this.model.get('name')) + "</a>");
    };

    return PersonItemView;

  })(Backbone.View);

}).call(this);
