// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.PersonListView = (function(_super) {
    __extends(PersonListView, _super);

    function PersonListView(el) {
      this.el = el;
      PersonListView.__super__.constructor.call(this, {
        initialize: function() {
          _.bindAll(this);
          this.collection = new Bolk.Persons;
          return this.render();
        },
        render: function() {
          return $(this.el).append('<ul></ul>');
        }
      });
    }

    return PersonListView;

  })(Backbone.View);

}).call(this);
