// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.PersonListView = (function(_super) {

    __extends(PersonListView, _super);

    function PersonListView() {
      return PersonListView.__super__.constructor.apply(this, arguments);
    }

    PersonListView.prototype.initialize = function() {
      var _this = this;
      _.bindAll(this);
      this.render();
      this.items = {};
      return this.model.forEach(function(person) {
        var li, _ref, _ref1, _ref2;
        _this.items[(_ref = person.get('uid')) != null ? _ref : person.cid] = new Bolk.PersonItemView({
          model: person
        });
        _this.$list.append((li = _this.items[(_ref1 = person.get('uid')) != null ? _ref1 : person.cid].$el));
        return li.attr('id', 'person-' + ((_ref2 = person.get('uid')) != null ? _ref2 : person.cid));
      });
    };

    PersonListView.prototype.render = function() {
      this.$el.append((this.$list = $('<ul class="members"></ul>')));
      return this;
    };

    PersonListView.prototype.remove = function() {
      return this.$el.children().remove();
    };

    return PersonListView;

  })(Backbone.View);

}).call(this);
