// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.MembersPage = (function(_super) {
    __extends(MembersPage, _super);

    function MembersPage(title) {
      var actions;

      if (title == null) {
        title = 'Ledenlijst';
      }
      MembersPage.__super__.constructor.call(this, title);
      actions = [];
      actions.push({
        link: '#/home',
        text: 'Home'
      });
      actions.push({
        link: '#/leden/oud',
        text: 'Oud-leden'
      });
      actions.push({
        link: '#/leden/kandidaat',
        text: 'Kandidaatleden'
      });
      this.contents.append(this._createActions(actions));
    }

    return MembersPage;

  })(Bolk.Page);

}).call(this);
