// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.MembersPage = (function(_super) {
    __extends(MembersPage, _super);

    function MembersPage(title) {
      if (title == null) {
        title = 'Members';
      }
      MembersPage.__super__.constructor.call(this, title);
    }

    MembersPage.prototype.display = function(list) {
      var _ref;

      if ((_ref = this.collectionView) != null) {
        _ref.remove();
      }
      return this.collectionView = new Bolk.PersonListView({
        el: this.contents,
        model: list
      });
    };

    return MembersPage;

  })(Bolk.Page);

}).call(this);
