// Generated by CoffeeScript 1.8.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.PageController = (function(_super) {
    __extends(PageController, _super);

    function PageController(view) {
      PageController.__super__.constructor.call(this, view);
      $('body').on('click', '[data-route]', this.navigate);
    }

    PageController.prototype.kill = function() {
      PageController.__super__.kill.apply(this, arguments);
      $('body').off('click', '[data-route]', this.navigate);
      return this;
    };

    PageController.prototype.navigate = function(event) {
      document.router.navigate('/' + $(event.currentTarget).data('route'), {
        trigger: true
      });
      event.stopPropagation();
      event.preventDefault();
      return false;
    };

    PageController.prototype.showLoader = function() {
      this.view.showLoader();
      return this;
    };

    PageController.prototype.hideLoader = function() {
      this.view.hideLoader();
      return this;
    };

    return PageController;

  })(Bolk.Controller);

}).call(this);
