// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.HomePageController = (function(_super) {

    __extends(HomePageController, _super);

    function HomePageController() {
      HomePageController.__super__.constructor.call(this, new Bolk.HomePage);
    }

    return HomePageController;

  })(Bolk.PageController);

}).call(this);
