// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.MemberPageController = (function(_super) {
    __extends(MemberPageController, _super);

    function MemberPageController(uid) {
      var _this = this;

      this.uid = uid;
      MemberPageController.__super__.constructor.call(this, new Bolk.MemberPage('member-' + this.id));
      locache.async.get('member-page').finished(function(data) {
        if (!data) {
          return _this._fetchMember();
        } else {
          return _this._displayMember(data);
        }
      });
    }

    MemberPageController.prototype._fetchMember = function() {
      var blip, el, v,
        _this = this;

      blip = new Bolk.BlipRequest("member/" + this.uid);
      blip.request.done(function(blipdata) {
        var operculum;

        operculum = new Bolk.OperculumRequest("member/" + _this.uid);
        return operculum.request.done(function(operculumdata) {
          var data;

          console.log(data = new Bolk.Person(_.extend(operculumdata, blipdata, {
            completed: true
          })));
          return _this._displayMember(data);
        });
      });
      this.view.contents.append((el = $('<form class="form-horizontal"></form>')));
      return v = new Bolk.PersonView({
        el: el,
        model: new Bolk.Person()
      }).render();
    };

    MemberPageController.prototype._displayMember = function(model) {};

    return MemberPageController;

  })(Bolk.PageController);

}).call(this);
