// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.SearchPageController = (function(_super) {
    __extends(SearchPageController, _super);

    function SearchPageController() {
      SearchPageController.__super__.constructor.call(this, new Bolk.SearchPage);
    }

    return SearchPageController;

  })(Bolk.PageController);

}).call(this);
