// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.MembersPageController = (function(_super) {

    __extends(MembersPageController, _super);

    MembersPageController.CacheTime = 120;

    function MembersPageController(filter) {
      var controller,
        _this = this;
      this.filter = filter;
      MembersPageController.__super__.constructor.call(this, new Bolk.MembersPage(this._titlefor(this.filter)));
      this.query = "membership:lid";
      locache.async.get('members-page').finished(function(data) {
        if (!data) {
          return _this._fetchMembers();
        } else {
          return _this._parseMembers(data);
        }
      });
      controller = this;
      this.search = $('input#search');
      this.search.val(this.query);
      this.search.keyup(function() {
        filter = controller.search.val().toLowerCase();
        return controller._filter(filter);
      });
    }

    MembersPageController.prototype._filter = function(query) {
      var person, _i, _len, _ref;
      this.query = query;
      if (this.query.length < 3) {
        this.query = "";
        this.view.display(this.model);
        return;
      }
      this.selection = new Bolk.Persons;
      console.log(this.query);
      _ref = this.model.models;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        person = _ref[_i];
        if (person.matches(this.query)) {
          this.selection.add(person);
        }
      }
      return this.view.display(this.selection);
    };

    MembersPageController.prototype._fetchMembers = function() {
      var blip,
        _this = this;
      this.showLoader();
      blip = new Bolk.BlipRequest('persons');
      return blip.request.always(function(data) {
        _this.hideLoader();
        if (blip.result) {
          data = blip.result;
          if (typeof data === String) {
            data = JSON.parse(data);
          }
          locache.async.set('members-page', data, MembersPageController.CacheTime);
          return _this._parseMembers(data);
        }
      });
    };

    MembersPageController.prototype._parseMembers = function(data) {
      var person, _i, _len;
      this.model = new Bolk.Persons();
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        person = data[_i];
        this.model.add(new Bolk.Person(_.extend(person, {
          complete: true
        })));
      }
      return this._filter(this.query);
    };

    MembersPageController.prototype._titlefor = function(filter) {
      switch (filter) {
        case 'kandidaat':
          return 'Kandidaatleden';
        case 'oud':
          return 'Oud-leden';
        case 'actief':
          return 'Ledenlijst';
        default:
          return 'Ledenlijst';
      }
    };

    return MembersPageController;

  })(Bolk.PageController);

}).call(this);
