// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Bolk.BlipRequest = (function(_super) {
    __extends(BlipRequest, _super);

    BlipRequest.EndPoint = 'http://blip.i.bolkhuis.nl/';

    function BlipRequest() {
      this.onSuccess = __bind(this.onSuccess, this);      Object.defineProperty(this, 'endpoint', {
        get: function() {
          return BlipRequest.EndPoint;
        }
      });
      BlipRequest.__super__.constructor.apply(this, [true].concat(__slice.call(arguments)));
    }

    BlipRequest.prototype.onSuccess = function(data) {
      var person, _i, _len, _results;

      switch (this.api) {
        case 'members':
          if (typeof data === String) {
            data = JSON.parse(data);
          }
          this.result = new Bolk.Persons();
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            person = data[_i];
            _results.push(this.result.add(new Bolk.Person(_.extend(person, {
              complete: true
            }))));
          }
          return _results;
          break;
        default:
          return this.result = data;
      }
    };

    return BlipRequest;

  })(Bolk.AjaxRequest);

}).call(this);
