// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Bolk.BlipRequest = (function(_super) {
    __extends(BlipRequest, _super);

    BlipRequest.EndPoint = '//blip.i.bolkhuis.nl/';

    function BlipRequest() {
      Object.defineProperty(this, 'endpoint', {
        get: function() {
          return BlipRequest.EndPoint;
        }
      });
      BlipRequest.__super__.constructor.apply(this, [true].concat(__slice.call(arguments)));
    }

    BlipRequest.prototype.onSuccess = function(data) {
      switch (this.api) {
        case '/members':
          return this.result = this.JSONToMembers(data);
        default:
          return this.result = data;
      }
    };

    BlipRequest.prototype.JSONtoMembers = function(json) {
      var person, result, _i, _len;

      result = new Bolk.Persons();
      for (_i = 0, _len = json.length; _i < _len; _i++) {
        person = json[_i];
        result.add(new Bolk.Person(_.extend(person, {
          complete: true
        })));
      }
      return result;
    };

    return BlipRequest;

  })(Bolk.AjaxRequest);

}).call(this);
