// Generated by CoffeeScript 1.6.2
(function() {
  Bolk.Session = (function() {
    function Session() {
      this.token = locache.get('session_token');
      Object.defineProperty(this, 'isLoggedIn', {
        get: function() {
          console.log(this.token, this.token != null);
          return this.token != null;
        }
      });
    }

    Session.prototype.oauth = function(cid, secret, redirect) {
      var state;

      if (cid == null) {
        cid = Bolk.clientId;
      }
      if (secret == null) {
        secret = Bolk.clientSecret;
      }
      if (redirect == null) {
        redirect = Bolk.baseUrl;
      }
      state = "__" + Math.random().toString().substring(2);
      return locache.async.set('session_token_state', state).finished(function() {
        return window.location = Bolk.OAuthEndpoint + "authorize?response_type=code" + ("&state=" + state) + ("&client_id=" + cid) + ("&client_pass=" + secret) + ("&redirect_uri=" + redirect);
      });
    };

    Session.prototype.login = function(code, state) {
      var promise,
        _this = this;

      promise = jQuery.Deferred();
      locache.async.get('session_token_state').finished(function(cached_state) {
        locache.remove('session_token_state');
        if (!cached_state || cached_state !== state) {
          promise.reject("Wrong state! Did you make this request? " + state + " : " + (typeof state) + " vs " + cached_state + " : " + (typeof cached_state) + " ");
          return false;
        }
        return Bolk.OAuthRequest.getAccessToken(code).request.done(function(data) {
          console.info("token data: " + (JSON.stringify(data)));
          _this.token = data.access_token;
          locache.set('session_token', data.access_token, data.expires_in - 60);
          locache.set('session_refresh_token', data.refresh_token, data.expires_in - 60);
          return promise.resolve(_this.token);
        }).fail(function(error) {
          return promise.reject(error);
        });
      });
      return promise.promise();
    };

    Session.prototype.unload = function() {
      return this;
    };

    Session.prototype.kill = function() {
      locache.remove('session_token');
      locache.remove('session_refresh_token');
      locache.flush();
      return this;
    };

    return Session;

  })();

}).call(this);
