// Generated by CoffeeScript 1.6.2
(function() {
  Bolk.Session = (function() {
    function Session() {
      this.token = locache.get('token');
    }

    Session.prototype.oauth = function(cid, secret, redirect) {
      if (cid == null) {
        cid = Bolk.clientId;
      }
      if (secret == null) {
        secret = Bolk.clientSecret;
      }
      if (redirect == null) {
        redirect = "http://ledenadmin.i.bolkhuis.nl/#/";
      }
      return window.location = "https://login.i.bolkhuis.com/" + ("authorize?client_id=" + cid + "&client_pass=" + secret + "&redirect_uri=" + redirect);
    };

    Session.prototype.login = function(code) {
      var _this = this;

      return Bolk.OAuthRequest.getAccessToken(code).execute().done(function(data) {
        return _this.token = data;
      });
    };

    Session.prototype.kill = function() {
      locache.remove('token');
      return locache.flush();
    };

    return Session;

  })();

}).call(this);
