// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.AppRouter = (function(_super) {
    __extends(AppRouter, _super);

    function AppRouter() {
      _ref = AppRouter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AppRouter.prototype.routes = {
      '': 'home',
      'home': 'home',
      'leden': 'members',
      'leden/:filter': 'members',
      'lid/:id': 'member'
    };

    AppRouter.prototype.initialize = function() {
      this.controller = null;
      Backbone.history.start();
      return console.debug('Finished initializing router');
    };

    AppRouter.prototype.home = function() {
      var _ref1;

      console.debug('Routing home');
      if ((_ref1 = this.controller) != null) {
        _ref1.kill();
      }
      return this.controller = new Bolk.HomePageController();
    };

    AppRouter.prototype.members = function(filter) {
      var _ref1;

      if (filter == null) {
        filter = 'actief';
      }
      console.debug('Routing members - ' + filter);
      if ((_ref1 = this.controller) != null) {
        _ref1.kill();
      }
      return this.controller = new Bolk.MembersPageController(filter);
    };

    AppRouter.prototype.member = function(id) {
      var _ref1;

      console.debug('Routing member:' + id);
      if ((_ref1 = this.controller) != null) {
        _ref1.kill();
      }
      return this.controller = new Bolk.MemberPageController(id);
    };

    return AppRouter;

  })(Backbone.Router);

}).call(this);
