// Generated by CoffeeScript 1.6.2
(function() {
  var doRequest;

  doRequest = function(event) {
    var elem, namespace, request, _ref;

    elem = $(event.target);
    namespace = ((_ref = typeof exports !== "undefined" && exports !== null ? exports : window) != null ? _ref : this)["Bolk"];
    request = new namespace[elem.data('endpoint')](elem.data('api'), elem.data('params'), elem.data('method'));
    window.history.pushState(request.statify(), document.title, elem.attr('href'));
    event.preventDefault();
    return false;
  };

  jQuery(document).ready(function() {
    return $('[data-endpoint]').each(function(i, elem) {
      return $(elem).on('click', doRequest);
    });
  });

}).call(this);
