// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Bolk = {
    version: '1.0.0',
    clientId: 'ledenadmin',
    clientSecret: 'ledenadmin'
  };

  locache.cachePrefix += '.bolk.';

  locache.expirePrefix += ".bolk.";

  locache.cleanup();

}).call(this);
