// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.BlipRequest = (function(_super) {
    __extends(BlipRequest, _super);

    BlipRequest.EndPoint = '//blip.i.bolkhuis.nl/';

    function BlipRequest() {
      Object.defineProperty(this, 'endpoint', {
        get: function() {
          return BlipRequest.EndPoint;
        }
      });
      BlipRequest.__super__.constructor.apply(this, arguments);
    }

    BlipRequest.prototype.onSuccess = function(data) {};

    return BlipRequest;

  })(Bolk.AjaxRequest);

}).call(this);
