// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bolk.Person = (function(_super) {
    __extends(Person, _super);

    function Person() {
      _ref = Person.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Person.prototype.defaults = {
      uid: '',
      nickname: '',
      study: '',
      alive: true,
      inauguration: null,
      resignation_letter: null,
      resignation: null,
      initials: '',
      firstname: '',
      lastname: '',
      email: '',
      gender: '',
      phone: '',
      mobile: '',
      phone_parents: '',
      address: '',
      dateofbirth: ''
    };

    return Person;

  })(Backbone.Model);

}).call(this);
